# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54b691c44ba4e36760a2057b3c55cbb5aeb7aaf1eb008ad1bc6f8f6ebca8b809208ea194e15d87a271fd1cf8823652d8ee86e787d685512860c8a7acfe5fa234

test:
  secret_key_base: 0155ef37d447a7bf605dc32288465e1d58146a83f2114686a638d9ce8ed7a08d3def3d9bb38985bc58271b58c738541b25bed3cf0b667b6813d84b13feb70aa1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
